export const CLIENT_SEARCH_DATA_REQUEST = "CLIENT_SEARCH_DATA_REQUEST";
export const CLIENT_SEARCH_DATA_SUCCESS = "CLIENT_SEARCH_DATA_SUCCESS";
export const CLIENT_SEARCH_DATA_FAILURE = "CLIENT_SEARCH_DATA_FAILURE";



export const DATE_LIST_DATA_SHOW_REQUEST = "DATE_LIST_DATA_SHOW_REQUEST";
export const DATE_LIST_DATA_SHOW_SUCCESS = "DATE_LIST_DATA_SHOW_SUCCESS";
export const DATE_LIST_DATA_SHOW_FAILURE = "DATE_LIST_DATA_SHOW_FAILURE";



export const ARR_LIST_DATA_SHOW_REQUEST = "ARR_LIST_DATA_SHOW_REQUEST";
export const ARR_LIST_DATA_SHOW_SUCCESS = "ARR_LIST_DATA_SHOW_SUCCESS";
export const ARR_LIST_DATA_SHOW_FAILURE = "ARR_LIST_DATA_SHOW_FAILURE";






export const INVOICE_DATA_LIST_REQUEST = "INVOICE_DATA_LIST_REQUEST";
export const INVOICE_DATA_LIST_SUCCESS = "INVOICE_DATA_LIST_SUCCESS";
export const INVOICE_DATA_LIST_FAILURE = "INVOICE_DATA_LIST_FAILURE";




export const VIEW_CONTACT_DB_DATA_LIST_REQUEST = "VIEW_CONTACT_DB_DATA_LIST_REQUEST";
export const VIEW_CONTACT_DB_DATA_LIST_SUCCESS = "VIEW_CONTACT_DB_DATA_LIST_SUCCESS";
export const VIEW_CONTACT_DB_DATA_LIST_FAILURE = "VIEW_CONTACT_DB_DATA_LIST_FAILURE";




export const GET_CUSTUMER_DATA_TOTAL_REQUEST = "GET_CUSTUMER_DATA_TOTAL_REQUEST";
export const GET_CUSTUMER_DATA_TOTAL_SUCCESS = "GET_CUSTUMER_DATA_TOTAL_SUCCESS";
export const GET_CUSTUMER_DATA_TOTAL_FAILURE = "GET_CUSTUMER_DATA_TOTAL_FAILURE";




export const GET_CUSTOMER_FILTER_DATA_REQUEST = "GET_CUSTOMER_FILTER_DATA_REQUEST";
export const GET_CUSTOMER_FILTER_DATA_SUCCESS = "GET_CUSTOMER_FILTER_DATA_SUCCESS";
export const GET_CUSTOMER_FILTER_DATA_FAILURE = "GET_CUSTOMER_FILTER_DATA_FAILURE";







export const GET_CONTRACT_DATA_DB_FILTER_REQUEST = "GET_CONTRACT_DATA_DB_FILTER_REQUEST";
export const GET_CONTRACT_DATA_DB_FILTER_SUCCESS = "GET_CONTRACT_DATA_DB_FILTER_SUCCESS";
export const GET_CONTRACT_DATA_DB_FILTER_FAILURE = "GET_CONTRACT_DATA_DB_FILTER_FAILURE";




