import { createStore, applyMiddleware, combineReducers } from "redux";
import thunk from "redux-thunk";
import { composeWithDevTools } from "redux-devtools-extension";

import {
  userLoginReducer,
  userRegisterReducer,
  userDetailsReducer,
  UpdateProfileReducer,
  userPortfolioReducer,
  getCreatorProfileJobsInProgressReducer,
  memberApproverJobsInProgressReducer,
  memberMarketerJobsInProgressReducer,
  getMemberAdminProfileJobsInProgressReducer,
  getAgencyRatingDetailsReducer,
  getCreatorRatingDetailsReducer,
  Cacheupdate,
  AllUsersListReducer,
} from "./redux/reducers/auth-reducer";
import { loaderReducer } from "./redux/reducers/other-reducer";

import {
  UploadFileReducer,
  GetProductServiceReducer,
  GetAddContractProductServiceReducer,
  GetListProductServiceNameReducer,
  GetListProductServiceTypeReducer,
  GetListRevenuReducer,
  AddProductServiceReducer,
  GetByIdProductReducer,
  AddContractReducer,
  CsvShowClientReducer,
  ViewContractDbReducer,
  ViewContractDbWihtoutPageReducer,
  getCutomerTotalReducer,
  getCutomerTotalFilterReducer,
  CsvViewContractDbReducer,
  ContractScreenReducer,
  ArrViewReducer,
  DeleteReducer2,
  ProductAddReducer,
  UpdateReducer,
  ContractUpdateReducer,
  InvoicegetReducer,
  CsvInvoicegetReducer,
  ExcelInvoicegetReducer,
  InvoicelistReducer,
  ArrlistReducer,
  UserlistReducer,
  UserlistAdminReducer,
  UserlistIDReducer,
  UserPostReducer,
  UserUpdateReducer,
  UserDeleteReducer,
  CloseGetReducer,
  LifeListReducer,
  QuickbookReducer,
  ClientarrReducer,
  ArrGracegetReducer,
  DatefilterReducer,
  GetContractDbFilterListReducer,
  Clientsearch,
  ArrClientsearch,
  Contractsearch,
  Contractscreenupdatesearch,
  pendingrenewalreducer,
  GetProductServiceAdminReducer,
  PostProductServiceAdminReducer,
  EditProductServiceAdminReducer,
  DeleteProductServiceAdminReducer,
  GetContractUploadReducer,
  GetAllCompanyNameReducer,
  CsvShowClientAdminReducer,
  GetListProductServiceNameAdminReducer,
  pendingAdminrenewalreducer,
  ProfileUpdateReducer,
  getAllSuperAdminReducer
} from "./redux/reducers/Admin-saasot-reducer";

import {
  ClientsearchDataUserReducer,
  DatefilterUserReducer,
  ArrlistUserReducer,
  InvoicegetUserReducer,
  ViewContractDbUserReducer,
  getCutomerTotalUserReducer,
  getCutomerTotalFilterUserReducer,
  GetContractDbFilterListUserReducer,
} from "./redux/reducers/UserDetailReducer";

const reducer = combineReducers({
  authReducer: userLoginReducer,
  userRegisterReducer,
  userPortfolioReducer,
  getCreatorProfileJobsInProgressReducer,
  memberApproverJobsInProgressReducer,
  memberMarketerJobsInProgressReducer,
  getMemberAdminProfileJobsInProgressReducer,
  UpdateProfileReducer,
  userDetailsReducer,
  loaderReducer,
  getAgencyRatingDetailsReducer,
  getCreatorRatingDetailsReducer,
  UploadFileReducer,
  GetProductServiceReducer,
  GetAddContractProductServiceReducer,
  GetListProductServiceNameReducer,
  GetListProductServiceTypeReducer,
  GetListRevenuReducer,
  AddProductServiceReducer,
  GetByIdProductReducer,
  AddContractReducer,
  CsvShowClientReducer,
  ViewContractDbReducer,
  ViewContractDbWihtoutPageReducer,
  getCutomerTotalReducer,
  getCutomerTotalFilterReducer,
  CsvViewContractDbReducer,
  ContractScreenReducer,
  ArrViewReducer,
  DeleteReducer2,
  ProductAddReducer,
  UpdateReducer,
  ContractUpdateReducer,
  InvoicegetReducer,
  CsvInvoicegetReducer,
  ExcelInvoicegetReducer,
  InvoicelistReducer,
  ArrlistReducer,
  Clientsearch,
  ArrClientsearch,
  UserlistReducer,
  UserlistAdminReducer,
  UserlistIDReducer,
  UserPostReducer,
  UserUpdateReducer,
  Contractscreenupdatesearch,
  UserDeleteReducer,
  CloseGetReducer,
  LifeListReducer,
  QuickbookReducer,
  ClientarrReducer,
  ArrGracegetReducer,
  Cacheupdate,
  DatefilterReducer,
  GetContractDbFilterListReducer,
  Contractsearch,
  pendingrenewalreducer,
  AllUsersListReducer,
  ClientsearchDataUserReducer,
  DatefilterUserReducer,
  ArrlistUserReducer,
  InvoicegetUserReducer,
  ViewContractDbUserReducer,
  getCutomerTotalUserReducer,
  getCutomerTotalFilterUserReducer,
  GetContractDbFilterListUserReducer,
  GetProductServiceAdminReducer,
  PostProductServiceAdminReducer,
  EditProductServiceAdminReducer,
  DeleteProductServiceAdminReducer,
  GetContractUploadReducer,
  GetAllCompanyNameReducer,
  CsvShowClientAdminReducer,
  GetListProductServiceNameAdminReducer,
  pendingAdminrenewalreducer,
  ProfileUpdateReducer,
  getAllSuperAdminReducer
});

// get userData from localStorage
const userDataFromStorage = localStorage.getItem("userData")
  ? JSON.parse(localStorage.getItem("userData"))
  : null;

// initialState
const initialState = {
  authReducer: { userData: userDataFromStorage },
};
// middleware used thunk
const middleware = [thunk];

// store variable initialized
const store = createStore(
  reducer,
  initialState,
  composeWithDevTools(applyMiddleware(...middleware))
);

export default store;
